apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hytale
resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
images:
  - name: ghcr.io/jski/hytale-server
    newTag: v2026.03.26-89796e57b
